export const data = [
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/02/2023",
    appointment_time: "02:00:00",
    signee_firstName: "Jim Rosa",
    signee_lastName: "Lane",
    signee_email: "Jimrosa@yahoo.com",
    notary_firstName: "Renee",
    notary_lastName: "Berryman",
    notary_email: "Reneeberryman@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/03/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Betty",
    signee_lastName: "Ward",
    signee_email: "Bettyward@yahoo.com",
    notary_firstName: "Stephanie",
    notary_lastName: "Mayberry",
    notary_email: "Stephanie Mayberry@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "11/01/2023",
    appointment_time: "01:00:00 ",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },
  {
    appointment_date: "01/01/2023",
    appointment_time: "01:00:00",
    signee_firstName: "Dusty",
    signee_lastName: "Kuvalis",
    signee_email: "Randy63@yahoo.com",
    notary_firstName: "John",
    notary_lastName: "Player",
    notary_email: "John Player@gmail.com",
    notarization_for: "Sale Deed",
    documents: "Sale Deed.pdf",
    status: "Open",
    action: "New Request",
  },

];

export const notification_data = [
  {
    notification_date: "01/01/2023",
    notification_time: "01:00:00",
    notification_for: "Admin",
    sender_name: "Kuvalis",
    subject: "Pending Signee registration verification",
    type: "Verification",
    action: "approve",
    notary_email: "John Player@gmail.com",
    markas_read: "Sale Deed",
    archive: "Sale Deed.pdf",
  },
  {
    notification_date: "01/01/2023",
    notification_time: "01:00:00",
    notification_for: "Admin",
    sender_name: "Kuvalis",
    subject: "Pending Signee registration verification",
    type: "Notarization request: assign",
    action: "approve",
    notary_email: "John Player@gmail.com",
    markas_read: "Sale Deed",
    archive: "Sale Deed.pdf",
  },
  {
    notification_date: "01/01/2023",
    notification_time: "01:00:00",
    notification_for: "Signee",
    sender_name: "Kuvalis",
    subject: "Welcome to eNotary",
    type: "Information",
    action: "reject",
    notary_email: "John Player@gmail.com",
    markas_read: "Sale Deed",
    archive: "Sale Deed.pdf",
  },
  {
    notification_date: "01/01/2023",
    notification_time: "01:00:00",
    notification_for: "Signee",
    sender_name: "Kuvalis",
    subject: "Welcome to eNotary",
    type: "Reminder; Scheduled Appointment",
    action: "review",
    notary_email: "John Player@gmail.com",
    markas_read: "Sale Deed",
    archive: "Sale Deed.pdf",
  },
];

export const org_data = [
  {
    org_name: "ABC Hospitals",
    org_type: "Hospital",
    contact_person: "Dusty",
    email: "Randy63@yahoo.com",
    phone: "2457884566",
    city: "any",
    reg_start_date: "01/01/2023",
    reg_end_date: "01/01/2023",
    status: "active",
  },
  {
    org_name: "ABC Hospitals",
    org_type: "Hospital",
    contact_person: "Dusty",
    email: "Randy63@yahoo.com",
    phone: "2457884566",
    city: "any",
    reg_start_date: "01/01/2023",
    reg_end_date: "01/01/2023",
    status: "inactive",
  },
  {
    org_name: "ABC Hospitals",
    org_type: "Hospital",
    contact_person: "Dusty",
    email: "Randy63@yahoo.com",
    phone: "2457884566",
    city: "any",
    reg_start_date: "01/01/2023",
    reg_end_date: "01/01/2023",
    status: "active",
  },
  {
    org_name: "ABC Hospitals",
    org_type: "Hospital",
    contact_person: "Dusty",
    email: "Randy63@yahoo.com",
    phone: "2457884566",
    city: "any",
    reg_start_date: "01/01/2023",
    reg_end_date: "01/01/2023",
    status: "inactive",
  },

];

export const user_data = [
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Signee",
    org_name: "None",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Signee (Client)",
    org_name: "Need44",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Client / Org. Admin",
    org_name: "ABC Hospitals",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Need44 Admin",
    org_name: "PQR Real Estates",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Notary",
    org_name: "",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Notary (Client)",
    org_name: "",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    email: "abc@pqr.com",
    roles: "Notary (Need44)",
    org_name: "",
  },

];
export const notary_validity_data = [
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    org_name: "Need44",
    documents_type1: "Driver's License",
    documents_pdf_type1: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type2: "Driver's License",
    documents_pdf_type2: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type3: "Driver's License",
    documents_pdf_type3: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",

  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    org_name: "Need44",
    documents_type1: "Driver's License",
    documents_pdf_type1: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type2: "Driver's License",
    documents_pdf_type2: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type3: "Driver's License",
    documents_pdf_type3: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",

  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    org_name: "ABC Hospitals",
    documents_type1: "Driver's License",
    documents_pdf_type1: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type2: "Driver's License",
    documents_pdf_type2: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type3: "Driver's License",
    documents_pdf_type3: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",

  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    org_name: "Need44",
    documents_type1: "Driver's License",
    documents_pdf_type1: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type2: "Driver's License",
    documents_pdf_type2: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type3: "Driver's License",
    documents_pdf_type3: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",

  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    org_name: "Need44",
    documents_type1: "Driver's License",
    documents_pdf_type1: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type2: "Driver's License",
    documents_pdf_type2: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",
    documents_type3: "Driver's License",
    documents_pdf_type3: "Document to View from List; Add some Icon to view the content",
    valid_till: "01/01/2023",

  },


];
export const user_validity_data = [
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    roles: "Signee",
    org_name: "Need44",
    documents_type: "Driver's License",
    documents_to_verify: "Document to View from List; Add some Icon to view the content",
    date_of_registration: "01/01/2023",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    roles: "Signee",
    org_name: "Need44",
    documents_type: "Driver's License",
    documents_to_verify: "Document to View from List; Add some Icon to view the content",
    date_of_registration: "01/01/2023",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    roles: "Signee",
    org_name: "Need44",
    documents_type: "Driver's License",
    documents_to_verify: "Document to View from List; Add some Icon to view the content",
    date_of_registration: "01/01/2023",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    roles: "Signee",
    org_name: "Need44",
    documents_type: "Driver's License",
    documents_to_verify: "Document to View from List; Add some Icon to view the content",
    date_of_registration: "01/01/2023",
  },
  {
    user_firstName: "John",
    user_lastName: "Player",
    user_email: "abc@pqr.com",
    roles: "Signee",
    org_name: "Need44",
    documents_type: "Driver's License",
    documents_to_verify: "Document to View from List; Add some Icon to view the content",
    date_of_registration: "01/01/2023",
  },
  

];
