const {
  VITE_SERVER_URL,
  VITE_WEBSOKET_URL,
  VITE_APRYSE_LICENCE_KEY,
  VITE_API_BASEURL,
} = import.meta.env;

export const SERVER_URL = VITE_SERVER_URL;
export const WEBSOKET_URL = VITE_WEBSOKET_URL;
export const APRYSE_LICENCE_KEY = VITE_APRYSE_LICENCE_KEY;
export const API_BASEURL = VITE_API_BASEURL;
